# Generated by Django 6.0.4 on 2026-05-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='valor_servico',
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='GastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do gasto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_extras', to='core.servico')),
            ],
        ),
    ]
