# Generated by Django 6.0.1 on 2026-02-02 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='servico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos_tecnico', to='core.empregado'),
        ),
    ]
