# Generated by Django 6.0.6 on 2026-06-20 16:11

import core.models
import utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='logo',
            field=models.ImageField(blank=True, upload_to=core.models.renomear_logo, validators=[utils.file_utils.validar_tamanho_arquivo], verbose_name='Logo'),
        ),
    ]
