# Generated by Django 6.0.6 on 2026-06-10 00:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servico_valor_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to=core.models.renomear_logo, verbose_name='Logo')),
                ('texto_cabecalho', models.TextField(blank=True, help_text='Texto exibido no cabeçalho do PDF exportado', verbose_name='Texto do Cabeçalho (PDF)')),
                ('texto_rodape', models.TextField(blank=True, help_text='Texto exibido no rodapé do PDF exportado', verbose_name='Texto do Rodapé (PDF)')),
                ('chave_pix', models.CharField(blank=True, max_length=200, verbose_name='Chave Pix')),
                ('tipo_chave_pix', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], max_length=10, verbose_name='Tipo da Chave Pix')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
