# Generated by Django 6.0.6 on 2026-06-12 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_configuracao_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='pecas_utilizadas',
        ),
        migrations.AddField(
            model_name='servico',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Causa do problema identificada pelo técnico', null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='servico',
            name='problema_relatado',
            field=models.TextField(blank=True, help_text='O que o cliente relatou como problema', null=True, verbose_name='Problema Relatado'),
        ),
        migrations.AddField(
            model_name='servico',
            name='solucao',
            field=models.TextField(blank=True, help_text='O que foi feito para resolver', null=True, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço'),
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Máquina')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº de Série')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='core.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='maquinas',
            field=models.ManyToManyField(blank=True, related_name='servicos', to='core.maquina'),
        ),
        migrations.CreateModel(
            name='PecaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Peça')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Qtd.')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor Total')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='core.servico')),
            ],
        ),
    ]
