# Generated by Django 6.0.6 on 2026-06-13 00:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_servico_pecas_utilizadas_servico_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.renomear_foto_maquina, verbose_name='Foto da Máquina'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
    ]
