# Generated by Django 6.0.6 on 2026-06-13 01:15

import django.core.validators
import django.db.models.deletion
import servicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_tiposervico',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço')),
                ('problema_relatado', models.TextField(blank=True, help_text='O que o cliente relatou como problema', null=True, verbose_name='Problema Relatado')),
                ('diagnostico', models.TextField(blank=True, help_text='Causa do problema identificada pelo técnico', null=True, verbose_name='Diagnóstico')),
                ('solucao', models.TextField(blank=True, help_text='O que foi feito para resolver', null=True, verbose_name='Solução')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_competencia', models.DateTimeField(blank=True, null=True)),
                ('km_rodado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hora_trabalhada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='clientes.cliente')),
                ('maquinas', models.ManyToManyField(blank=True, db_table='core_servico_maquinas', related_name='servicos', to='clientes.maquina')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos_tecnico', to='funcionarios.empregado')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos_tipo', to='servicos.tiposervico')),
            ],
            options={
                'db_table': 'core_servico',
            },
        ),
        migrations.CreateModel(
            name='PecaUtilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Peça')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Qtd.')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Valor Total')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='servicos.servico')),
            ],
            options={
                'db_table': 'core_pecautilizada',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota_fiscal', models.CharField(max_length=50, unique=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao_nota', models.TextField(blank=True, null=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='servicos.servico')),
            ],
            options={
                'db_table': 'core_notafiscal',
            },
        ),
        migrations.CreateModel(
            name='GastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do gasto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_extras', to='servicos.servico')),
            ],
            options={
                'db_table': 'core_gastoextra',
            },
        ),
        migrations.CreateModel(
            name='AnexoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=servicos.models.renomear_anexo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi'])], verbose_name='Anexo')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='servicos.servico')),
            ],
            options={
                'db_table': 'core_anexoservico',
            },
        ),
    ]
