# Generated by Django 6.0.6 on 2026-06-20 16:11

import django.core.validators
import servicos.models
import utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoservico',
            name='arquivo',
            field=models.FileField(upload_to=servicos.models.renomear_anexo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi']), utils.file_utils.validar_tamanho_arquivo], verbose_name='Anexo'),
        ),
    ]
