# Generated by Django 6.1 on 2026-09-15 23:00

import django.db.models.deletion
from django.db import migrations, models


def copiar_tipos_existentes(apps, schema_editor):
    Servico = apps.get_model('servicos', 'Servico')
    ServicoTipo = apps.get_model('servicos', 'ServicoTipo')
    ServicoTipo.objects.using(schema_editor.connection.alias).bulk_create([
        ServicoTipo(servico_id=servico.pk, tipo_servico_id=servico.tipo_servico_id)
        for servico in Servico.objects.using(schema_editor.connection.alias).all().iterator()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_recalcula_data_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_servico', to='servicos.servico')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.tiposervico')),
            ],
            options={
                'db_table': 'core_servicotipo',
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='tipos_servico',
            field=models.ManyToManyField(related_name='servicos_tipo', through='servicos.ServicoTipo', to='servicos.tiposervico'),
        ),
        migrations.AddConstraint(
            model_name='servicotipo',
            constraint=models.UniqueConstraint(fields=('servico', 'tipo_servico'), name='servicotipo_unico_por_os'),
        ),
        migrations.RunPython(copiar_tipos_existentes, migrations.RunPython.noop),
        migrations.RemoveField(model_name='servico', name='tipo_servico'),
    ]
