# Generated by Django 6.1 on 2026-09-16 00:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_os_multiplos_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicotipo',
            name='valor_aplicado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do serviço (R$)'),
        ),
        migrations.AddField(
            model_name='tiposervico',
            name='valor_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Usado como sugestão ao adicionar o tipo a uma OS.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor padrão (R$)'),
        ),
    ]
