# Generated by Django 6.1 on 2026-09-16 01:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_valores_por_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto (%) ou (R$)'),
        ),
        migrations.AddField(
            model_name='servico',
            name='tipo_desconto',
            field=models.CharField(choices=[('NENHUM', 'Sem desconto'), ('PERCENTUAL', 'Porcentagem (%)'), ('VALOR', 'Valor fixo (R$)')], default='NENHUM', max_length=10, verbose_name='Tipo de desconto'),
        ),
    ]
