# Generated by Django 6.0.6 on 2026-06-20 16:11

import clientes.models
import utils.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=clientes.models.renomear_foto_maquina, validators=[utils.file_utils.validar_tamanho_arquivo], verbose_name='Foto da Máquina'),
        ),
    ]
